# Generated by Django 4.1.1 on 2022-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Album Name'),
        ),
    ]
